/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package weather;

/**
 *
 * @author 7h3n3w3r4cr4ck3r
 */
public class Mexico extends javax.swing.JFrame {
        public String pais= "Mexico";        
        public String BajaCaliforniaSurtxt = "Baja California Sur";
        public String Michoacantxt = "Michoacan";
        public String Colimatxt = "Colima";
        public String Jaliscotxt = "Jalisco";
        public String Zacatecastxt =  "Zacatecas";
        public String BajaCaliforniaNortetxt = "Baja California Norte";
        public String Tamaulipastxt = "Tamaulipas";
        public String Guerrerotxt = "Gerrero";
        public String Cancuntxt = "Cancun";
        public String Nuevoleontxt = "Nuevo Leon";
        public String Chihuahuatxt = "Chihuahua";
        public String Sonoratxt = "Sonora";
        public String Yucatantxt = "Yucatan";
        public String Coahuilatxt = "Coahuila";
        public String Durangotxt = "Durango";
        public String Sinaloatxt = "Sinaloa";
        public String Quintanarootxt = "Quitana Roo";
        public String Campechetxt = "Campeche";
        public String Monterreytxt = "Monterrey";
        public String SanLuisPotositxt = "San Luis Potosi";
        public String Guanajuatotxt = "Guanajuato";
        public String Nayarittxt = "Nayarit";
        public String Aguascalientestxt = "Aguascalientes";
        public String Veracruztxt = "Veracruz";
        public String Pueblatxt = "Puebla";
        public String EstadodeMexicotxt = "Estado de Mexico";
        public String Hidalgotxt = "Hidalgo";
        public String Morelostxt = "Morelos";
        public String Oaxacatxt = "Oaxaca";
        public String Tlaxcalatxt = "Tlaxcala";
        public String MexicoDFtxt = "Distrito Federal";
        public String Tabascotxt = "Tabasco";
    /**
     * Creates new form Mexico
     */
    public Mexico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MexicoDF = new javax.swing.JButton();
        Resutado = new javax.swing.JTextField();
        BajaCaliforniaSur = new javax.swing.JButton();
        BajaCaliforniaNorte = new javax.swing.JButton();
        Sonora = new javax.swing.JButton();
        Chihuahua = new javax.swing.JButton();
        Coahuila = new javax.swing.JButton();
        NuevoLeon = new javax.swing.JButton();
        Tamaulipas = new javax.swing.JButton();
        Durango = new javax.swing.JButton();
        Sinaloa = new javax.swing.JButton();
        SanLuisPotosi = new javax.swing.JButton();
        Nayarit = new javax.swing.JButton();
        Zacatecas = new javax.swing.JButton();
        Jalisco = new javax.swing.JButton();
        Aguascalientes = new javax.swing.JButton();
        Colima = new javax.swing.JButton();
        Queretaro = new javax.swing.JButton();
        Michoacan = new javax.swing.JButton();
        EstadodeMexico = new javax.swing.JButton();
        Guanajuato = new javax.swing.JButton();
        Guerrero = new javax.swing.JButton();
        Morelos = new javax.swing.JButton();
        Puebla = new javax.swing.JButton();
        Veracruz = new javax.swing.JButton();
        Oaxaca = new javax.swing.JButton();
        Chiapas = new javax.swing.JButton();
        Tlaxcala = new javax.swing.JButton();
        Tabasco = new javax.swing.JButton();
        Campeche = new javax.swing.JButton();
        Quintanaroo = new javax.swing.JButton();
        Yucatan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mapa de México");

        MexicoDF.setText("Mexico DF");
        MexicoDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MexicoDFActionPerformed(evt);
            }
        });

        BajaCaliforniaSur.setText("Baja California Sur");
        BajaCaliforniaSur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajaCaliforniaSurActionPerformed(evt);
            }
        });

        BajaCaliforniaNorte.setText("Baja Calfornia Norte");
        BajaCaliforniaNorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajaCaliforniaNorteActionPerformed(evt);
            }
        });

        Sonora.setText("Sonora");
        Sonora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SonoraActionPerformed(evt);
            }
        });

        Chihuahua.setText("Chihuahua");
        Chihuahua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChihuahuaActionPerformed(evt);
            }
        });

        Coahuila.setText("Coahuila");
        Coahuila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoahuilaActionPerformed(evt);
            }
        });

        NuevoLeon.setText("Nuevo Leon");
        NuevoLeon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoLeonActionPerformed(evt);
            }
        });

        Tamaulipas.setText("Tamaulipas");
        Tamaulipas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TamaulipasActionPerformed(evt);
            }
        });

        Durango.setText("Durango");
        Durango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DurangoActionPerformed(evt);
            }
        });

        Sinaloa.setText("Sinaloa");
        Sinaloa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinaloaActionPerformed(evt);
            }
        });

        SanLuisPotosi.setText("San Luis Potosi");
        SanLuisPotosi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SanLuisPotosiActionPerformed(evt);
            }
        });

        Nayarit.setText("Nayarit");
        Nayarit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NayaritActionPerformed(evt);
            }
        });

        Zacatecas.setText("Zacatecas");
        Zacatecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZacatecasActionPerformed(evt);
            }
        });

        Jalisco.setText("Jalisco");
        Jalisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JaliscoActionPerformed(evt);
            }
        });

        Aguascalientes.setText("Aguascalientes");
        Aguascalientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AguascalientesActionPerformed(evt);
            }
        });

        Colima.setText("Colima");
        Colima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColimaActionPerformed(evt);
            }
        });

        Queretaro.setText("Queretaro");
        Queretaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueretaroActionPerformed(evt);
            }
        });

        Michoacan.setText("Michoacan");
        Michoacan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MichoacanActionPerformed(evt);
            }
        });

        EstadodeMexico.setText("Estado de Mexico");
        EstadodeMexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadodeMexicoActionPerformed(evt);
            }
        });

        Guanajuato.setText("Guanajuato");
        Guanajuato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuanajuatoActionPerformed(evt);
            }
        });

        Guerrero.setText("Guerrero");
        Guerrero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuerreroActionPerformed(evt);
            }
        });

        Morelos.setText("Morelos");
        Morelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MorelosActionPerformed(evt);
            }
        });

        Puebla.setText("Puebla");
        Puebla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PueblaActionPerformed(evt);
            }
        });

        Veracruz.setText("Veracruz");
        Veracruz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VeracruzActionPerformed(evt);
            }
        });

        Oaxaca.setText("Oaxaca");
        Oaxaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OaxacaActionPerformed(evt);
            }
        });

        Chiapas.setText("Chiapas");
        Chiapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChiapasActionPerformed(evt);
            }
        });

        Tlaxcala.setText("Tlaxcala");
        Tlaxcala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TlaxcalaActionPerformed(evt);
            }
        });

        Tabasco.setText("Tabasco");
        Tabasco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TabascoActionPerformed(evt);
            }
        });

        Campeche.setText("Campeche");
        Campeche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampecheActionPerformed(evt);
            }
        });

        Quintanaroo.setText("Quintanaroo");
        Quintanaroo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuintanarooActionPerformed(evt);
            }
        });

        Yucatan.setText("Yucatan");
        Yucatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YucatanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Tamaulipas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Durango)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Sinaloa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Chihuahua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Zacatecas)
                                .addGap(130, 130, 130)
                                .addComponent(Aguascalientes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Nayarit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MexicoDF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Coahuila)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BajaCaliforniaNorte)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BajaCaliforniaSur)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Sonora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NuevoLeon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SanLuisPotosi))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jalisco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Colima)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EstadodeMexico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Michoacan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Guanajuato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Guerrero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Queretaro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Puebla))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Morelos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Veracruz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Oaxaca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Chiapas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Tlaxcala)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Quintanaroo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Yucatan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Tabasco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Campeche))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(Resutado, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MexicoDF)
                    .addComponent(Coahuila)
                    .addComponent(BajaCaliforniaNorte)
                    .addComponent(BajaCaliforniaSur)
                    .addComponent(Sonora)
                    .addComponent(NuevoLeon)
                    .addComponent(SanLuisPotosi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tamaulipas)
                    .addComponent(Durango)
                    .addComponent(Sinaloa)
                    .addComponent(Chihuahua)
                    .addComponent(Zacatecas)
                    .addComponent(Aguascalientes)
                    .addComponent(Nayarit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jalisco)
                    .addComponent(Colima)
                    .addComponent(EstadodeMexico)
                    .addComponent(Michoacan)
                    .addComponent(Guanajuato)
                    .addComponent(Guerrero)
                    .addComponent(Queretaro)
                    .addComponent(Puebla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Morelos)
                    .addComponent(Veracruz)
                    .addComponent(Oaxaca)
                    .addComponent(Chiapas)
                    .addComponent(Tlaxcala)
                    .addComponent(Quintanaroo)
                    .addComponent(Yucatan)
                    .addComponent(Tabasco)
                    .addComponent(Campeche))
                .addGap(27, 27, 27)
                .addComponent(Resutado, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MexicoDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MexicoDFActionPerformed
        Resutado.setText(getWeather(MexicoDFtxt, pais));
    }//GEN-LAST:event_MexicoDFActionPerformed

    private void CoahuilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoahuilaActionPerformed
        Resutado.setText(getWeather(Coahuilatxt, pais)); 
    }//GEN-LAST:event_CoahuilaActionPerformed

    private void BajaCaliforniaNorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajaCaliforniaNorteActionPerformed
        Resutado.setText(getWeather(BajaCaliforniaNortetxt, pais));
    }//GEN-LAST:event_BajaCaliforniaNorteActionPerformed

    private void BajaCaliforniaSurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajaCaliforniaSurActionPerformed
        Resutado.setText(getWeather(BajaCaliforniaSurtxt, pais)); 
    }//GEN-LAST:event_BajaCaliforniaSurActionPerformed

    private void SonoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SonoraActionPerformed
        Resutado.setText(getWeather(Sonoratxt, pais));
    }//GEN-LAST:event_SonoraActionPerformed

    private void NuevoLeonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoLeonActionPerformed
        Resutado.setText(getWeather(Nuevoleontxt, pais)); 
    }//GEN-LAST:event_NuevoLeonActionPerformed

    private void SanLuisPotosiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SanLuisPotosiActionPerformed
        Resutado.setText(getWeather(SanLuisPotositxt, pais)); 
    }//GEN-LAST:event_SanLuisPotosiActionPerformed

    private void TamaulipasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TamaulipasActionPerformed
        Resutado.setText(getWeather(Tamaulipastxt, pais)); 
    }//GEN-LAST:event_TamaulipasActionPerformed

    private void DurangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DurangoActionPerformed
        Resutado.setText(getWeather(Durangotxt, pais)); 
    }//GEN-LAST:event_DurangoActionPerformed

    private void SinaloaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinaloaActionPerformed
        Resutado.setText(getWeather(Sinaloatxt, pais));
    }//GEN-LAST:event_SinaloaActionPerformed

    private void ChihuahuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChihuahuaActionPerformed
        Resutado.setText(getWeather(Chihuahuatxt, pais));
    }//GEN-LAST:event_ChihuahuaActionPerformed

    private void ZacatecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZacatecasActionPerformed
        Resutado.setText(getWeather(Zacatecastxt, pais)); 
    }//GEN-LAST:event_ZacatecasActionPerformed

    private void AguascalientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AguascalientesActionPerformed
        Resutado.setText(getWeather(Aguascalientestxt, pais));
    }//GEN-LAST:event_AguascalientesActionPerformed

    private void NayaritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NayaritActionPerformed
        Resutado.setText(getWeather(Nayarittxt, pais)); 
    }//GEN-LAST:event_NayaritActionPerformed

    private void JaliscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JaliscoActionPerformed
        Resutado.setText(getWeather(Jaliscotxt, pais)); 
    }//GEN-LAST:event_JaliscoActionPerformed

    private void ColimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColimaActionPerformed
        Resutado.setText(getWeather(Colimatxt, pais));
    }//GEN-LAST:event_ColimaActionPerformed

    private void EstadodeMexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadodeMexicoActionPerformed
        Resutado.setText(getWeather(EstadodeMexicotxt, pais));
    }//GEN-LAST:event_EstadodeMexicoActionPerformed

    private void MichoacanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MichoacanActionPerformed
        Resutado.setText(getWeather(Michoacantxt, pais));
    }//GEN-LAST:event_MichoacanActionPerformed

    private void GuanajuatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuanajuatoActionPerformed
        Resutado.setText(getWeather(Guanajuatotxt, pais)); 
    }//GEN-LAST:event_GuanajuatoActionPerformed

    private void GuerreroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuerreroActionPerformed
        Resutado.setText(getWeather(Guerrerotxt, pais));  
    }//GEN-LAST:event_GuerreroActionPerformed

    private void QueretaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueretaroActionPerformed
        Resutado.setText(getWeather(Quintanarootxt, pais));
    }//GEN-LAST:event_QueretaroActionPerformed

    private void PueblaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PueblaActionPerformed
        Resutado.setText(getWeather(Pueblatxt, pais)); 
    }//GEN-LAST:event_PueblaActionPerformed

    private void MorelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MorelosActionPerformed
        Resutado.setText(getWeather(Morelostxt, pais)); 
    }//GEN-LAST:event_MorelosActionPerformed

    private void VeracruzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeracruzActionPerformed
        Resutado.setText(getWeather(Veracruztxt, pais)); 
    }//GEN-LAST:event_VeracruzActionPerformed

    private void OaxacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OaxacaActionPerformed
        Resutado.setText(getWeather(Oaxacatxt, pais)); 
    }//GEN-LAST:event_OaxacaActionPerformed

    private void ChiapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChiapasActionPerformed
        Resutado.setText(getWeather(Chihuahuatxt, pais));  
        
    }//GEN-LAST:event_ChiapasActionPerformed

    private void TlaxcalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TlaxcalaActionPerformed
        Resutado.setText(getWeather(Tlaxcalatxt, pais));
    }//GEN-LAST:event_TlaxcalaActionPerformed

    private void QuintanarooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuintanarooActionPerformed
        Resutado.setText(getWeather(Quintanarootxt, pais));  
    }//GEN-LAST:event_QuintanarooActionPerformed

    private void YucatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YucatanActionPerformed
        Resutado.setText(getWeather(Yucatantxt, pais)); 
    }//GEN-LAST:event_YucatanActionPerformed

    private void TabascoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TabascoActionPerformed
        Resutado.setText(getWeather(Tabascotxt, pais)); 
    }//GEN-LAST:event_TabascoActionPerformed

    private void CampecheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampecheActionPerformed
        Resutado.setText(getWeather(Campechetxt, pais));
    }//GEN-LAST:event_CampecheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mexico().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aguascalientes;
    private javax.swing.JButton BajaCaliforniaNorte;
    private javax.swing.JButton BajaCaliforniaSur;
    private javax.swing.JButton Campeche;
    private javax.swing.JButton Chiapas;
    private javax.swing.JButton Chihuahua;
    private javax.swing.JButton Coahuila;
    private javax.swing.JButton Colima;
    private javax.swing.JButton Durango;
    private javax.swing.JButton EstadodeMexico;
    private javax.swing.JButton Guanajuato;
    private javax.swing.JButton Guerrero;
    private javax.swing.JButton Jalisco;
    private javax.swing.JButton MexicoDF;
    private javax.swing.JButton Michoacan;
    private javax.swing.JButton Morelos;
    private javax.swing.JButton Nayarit;
    private javax.swing.JButton NuevoLeon;
    private javax.swing.JButton Oaxaca;
    private javax.swing.JButton Puebla;
    private javax.swing.JButton Queretaro;
    private javax.swing.JButton Quintanaroo;
    private javax.swing.JTextField Resutado;
    private javax.swing.JButton SanLuisPotosi;
    private javax.swing.JButton Sinaloa;
    private javax.swing.JButton Sonora;
    private javax.swing.JButton Tabasco;
    private javax.swing.JButton Tamaulipas;
    private javax.swing.JButton Tlaxcala;
    private javax.swing.JButton Veracruz;
    private javax.swing.JButton Yucatan;
    private javax.swing.JButton Zacatecas;
    // End of variables declaration//GEN-END:variables

    private static String getCitiesByCountry(java.lang.String countryName) {
        WeatherMexico.GlobalWeather service = new WeatherMexico.GlobalWeather();
        WeatherMexico.GlobalWeatherSoap port = service.getGlobalWeatherSoap();
        return port.getCitiesByCountry(countryName);
    }

    private static String getWeather(java.lang.String cityName, java.lang.String countryName) {
        WeatherMexico.GlobalWeather service = new WeatherMexico.GlobalWeather();
        WeatherMexico.GlobalWeatherSoap port = service.getGlobalWeatherSoap();
        return port.getWeather(cityName, countryName);
    }
}
